server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Repassa /api/* para o container da API pela rede interna do compose
    location /api/ {
        proxy_pass http://api:8000/;
    }
}
